-- Create currencies table first (for foreign key constraint)
CREATE TABLE currencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(3) NOT NULL,
    exchange_rate DECIMAL(15,6) NOT NULL CHECK (exchange_rate > 0),
    PRIMARY KEY (id),
    CONSTRAINT uk_currencies_name UNIQUE (name)
);

-- Create departments table
CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    daily_budget DECIMAL(15,2) CHECK (daily_budget >= 0),
    monthly_budget DECIMAL(15,2) NOT NULL CHECK (monthly_budget >= 0),
    currency_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (currency_id) REFERENCES currencies(id)
);

-- Create users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL CHECK (role IN ('FINANCE', 'MANAGER', 'EMPLOYEE')),
    name VARCHAR(255) NOT NULL,
    department_id BIGINT,
    manager_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    FOREIGN KEY (department_id) REFERENCES departments(id),
    FOREIGN KEY (manager_id) REFERENCES users(id)
);

-- Create expense_categories table
CREATE TABLE expense_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    daily_budget DECIMAL(15,2) NOT NULL CHECK (daily_budget >= 0),
    monthly_budget DECIMAL(15,2) NOT NULL CHECK (monthly_budget >= 0),
    currency_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT uk_expense_categories_name UNIQUE (name),
    FOREIGN KEY (currency_id) REFERENCES currencies(id)
);

-- Create expenses table
CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    amount DECIMAL(15,2) NOT NULL CHECK (amount > 0),
    description VARCHAR(500),
    expense_date DATE NOT NULL,
    user_id BIGINT NOT NULL,
    expense_category_id BIGINT NOT NULL,
    currency_id BIGINT NOT NULL,
    receipt_url VARCHAR(1000),
    status VARCHAR(50) NOT NULL CHECK (status IN ('PENDING', 'APPROVED_BY_MANAGER', 'APPROVED_BY_FINANCE', 'REJECTED', 'REQUIRES_REVISION')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_expenses_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_expenses_expense_category FOREIGN KEY (expense_category_id) REFERENCES expense_categories(id),
    CONSTRAINT fk_expenses_currency FOREIGN KEY (currency_id) REFERENCES currencies(id)
);

-- Create alerts table
CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(50) NOT NULL CHECK (type IN ('CATEGORY', 'DEPARTMENT', 'ALL')),
    message VARCHAR(2000) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('NEW', 'RESOLVED')),
    expense_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (expense_id) REFERENCES expenses(id)
);

-- Create REVINFO table for Hibernate Envers
CREATE TABLE REVINFO (
    REV INTEGER GENERATED BY DEFAULT AS IDENTITY,
    REVTSTMP BIGINT,
    PRIMARY KEY (REV)
);
