CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(50) NOT NULL CHECK (type IN ('CATEGORY', 'DEPARTMENT', 'ALL')),
    message VARCHAR(500) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('NEW', 'RESOLVED')),
    expense_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (expense_id) REFERENCES expenses(id)
);
